- name: Open ports for k8s for http traffic
  ufw:
    rule: allow
    port: "{{item}}"
  loop:
    - "6443/tcp"
    - "2379:2380/tcp"
    - "10250/tcp"
    - "10259/tcp"
    - "10257/tcp"
    - "30000:32767/tcp"

- name: Enable Masquerading
  ufw:
    rule: masquerade
    direction: forward

- name: Reload UFW
  service:
    name: ufw
    state: reloaded
