- name: Open ports for k8s for http traffic
  ansible.builtin.command: firewall-cmd --zone=trusted --add-port={{item}} --permanent
  loop:
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250/tcp"
    - "10259/tcp"
    - "10257/tcp"
    - "30000-32767/tcp"

- name: "Set masquerade on trusted zone"
  ansible.builtin.command: firewall-cmd --zone=trusted --add-masquerade --permanent

- name: "Set masquerade"
  command: "firewall-cmd --add-masquerade --permanent"

- name: Firewalld reload
  systemd:
    name: firewalld
    state: reloaded
